### ISSUE TITLE
Build lantern stocklist

### ISSUE THREAD

**Issue by wjdp** [newtheatre/lx#1]
Currently:

```
- fixture:
  brand: Selecon
  model: Rama
  type: Fresnel
  stock:
    good: 10
    repair: 2
    broken: 0
```

want to include other fun stuff like:
- type: profile/fresnel/flood...
- beam angle/angle range
- power
- lumen output
- weight
- &c
