### ISSUE TITLE
GOBOs

### ISSUE THREAD

**Issue by wjdp** [newtheatre/lx#5]
```
- gobo:
  make: Rosco
  number: P12345
  name: Leafy leafy
  type: Breakup
  image: rosco-p12345.png
  stock:
    - size: M
      qty: 3
    - size: B
      qty: 1
```
